[package]
name = "chatt-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
env_logger = "0.11"
gpui = { path = "/code/ref/zed/crates/gpui" }
gpui_platform = { path = "/code/ref/zed/crates/gpui_platform", features = ["font-kit", "wayland", "x11"] }
image = { version = "0.25", default-features = false }
libmpv2 = { version = "6", default-features = false }
libmpv2-sys = "4.0.1"
rpc = { path = "../chatt/crates/rpc" }
unicode-segmentation = "1"
aws-lc-rs = { version = "1.17", default-features = false, features = ["alloc", "non-fips"] }
tempfile = "3"

[profile.dist]
inherits = "release"
lto = "fat"
codegen-units = 1
