#version 450
layout(local_size_x=8, local_size_y=8, local_size_z=1) in;
layout(set=0, binding=0) uniform sampler2D source_tex;
layout(set=0, binding=1, rgba16f) uniform writeonly image2D target_tex;
void main() {
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    vec2 coord = (vec2(pixel) + vec2(0.5)) / vec2(imageSize(target_tex));
    imageStore(target_tex, pixel, textureLod(source_tex, coord, 0.0));
}
