#version 450
#extension GL_ARB_compute_shader : enable
#extension GL_ARB_shader_image_load_store : enable

layout(binding=0, rgba32ui) writeonly restrict uniform uimage2D output_image;
layout(local_size_x=8, local_size_y=8) in;

void main() {
    uvec2 offset = 8u * (gl_WorkGroupID.xy % 2u);
    offset += gl_LocalInvocationID.xy;
    imageStore(output_image, ivec2(gl_GlobalInvocationID.xy), uvec4(offset, 0u, 1u));
}
