#version 450
#extension GL_ARB_compute_shader : enable
#extension GL_ARB_shader_storage_buffer_object : enable

layout(constant_id=0) const uint src_offset = 1;
layout(constant_id=1) const uint dst_offset = 1;
layout(std430, binding=0) readonly restrict buffer Src {
    layout(offset=0) uint src[256];
};
layout(std430, binding=1) writeonly restrict buffer Dst {
    layout(offset=0) uint dst[256];
};
layout(local_size_x=256, local_size_y=1) in;

void main() {
    uint word = src[src_offset + gl_GlobalInvocationID.x];
    word = (word & 0xFF00FF00u) >> 8 |
           (word & 0x00FF00FFu) << 8;
    dst[dst_offset + gl_GlobalInvocationID.x] = word;
}
